name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        repository: KhronosGroup/Vulkan-Headers
        path: Vulkan-Headers
    - name: build
      shell: bash
      run: |
        mv Vulkan-Headers ~/Vulkan-Headers
        export VULKAN_SDK=~/Vulkan-Headers
        test/run_tests.sh
